version: "3"
services:
  api:
    image: "test"
    depends_on:
      - web
    environment:
      HOST: db
      USER: root
      PASSWORD: "root"
      IP: "192.168.1.103"
      PORT: "8080"
  web:
    image: "phpmyadmin"
    depends_on:
      - db
    environment:
      PMA-HOST: db
      PMA-USER: root
      PMA-PASSWORD: "root"
    ports:
     - "8089:80"
  db:
    image: "mysql:5.7"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - "./testdb:/var/lib/mysql"


    
